
variable: /v3/api-docs

server:
  port: 8080

logging:
  file:
    name: log/logfile.log
    path: log/
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
resourceUrl: https://jsonplaceholder.typicode.com/posts
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
  jpa:
    hibernate:
      ddl-auto: none
      
